/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Nonename
 */
public class Añosform extends javax.swing.JInternalFrame {

    /**
     * Creates new form Años
     */
    public Añosform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtaño = new javax.swing.JTextField();
        cbxestado = new javax.swing.JComboBox<>();
        dateinicio = new com.toedter.calendar.JDateChooser();
        btnbuscar = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        datefin = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatos = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.icon.checkmarkColor"));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtaño.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Año", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtaño.setMinimumSize(new java.awt.Dimension(64, 40));
        txtaño.setPreferredSize(new java.awt.Dimension(67, 40));
        jPanel2.add(txtaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, -1));

        cbxestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activo", "no activo" }));
        cbxestado.setToolTipText("");
        cbxestado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxestado.setName(""); // NOI18N
        cbxestado.setPreferredSize(new java.awt.Dimension(72, 50));
        jPanel2.add(cbxestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 50));

        dateinicio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inicio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        dateinicio.setMinimumSize(new java.awt.Dimension(92, 50));
        dateinicio.setPreferredSize(new java.awt.Dimension(95, 50));
        jPanel2.add(dateinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 52));

        btnbuscar.setText("Buscar");
        jPanel2.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 220, -1));

        btnregistrar.setText("Registrar");
        jPanel2.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 220, -1));

        btneditar.setText("Editar");
        jPanel2.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 220, -1));

        btneliminar.setText("Eliminar");
        jPanel2.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 220, -1));

        btnlimpiar.setText("Limpiar");
        jPanel2.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 220, -1));

        datefin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        datefin.setMinimumSize(new java.awt.Dimension(92, 50));
        datefin.setPreferredSize(new java.awt.Dimension(95, 50));
        jPanel2.add(datefin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 52));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 590));

        tbldatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbldatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 840, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btneditar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnlimpiar;
    public javax.swing.JButton btnregistrar;
    public javax.swing.JComboBox<String> cbxestado;
    public com.toedter.calendar.JDateChooser datefin;
    public com.toedter.calendar.JDateChooser dateinicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbldatos;
    public javax.swing.JTextField txtaño;
    // End of variables declaration//GEN-END:variables
}
