/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Nonename
 */
public class Estudiantesform extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estudiantes
     */
    public Estudiantesform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtdni = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido1 = new javax.swing.JTextField();
        txtapellido2 = new javax.swing.JTextField();
        cbxsexo = new javax.swing.JComboBox<>();
        datenacimiento = new com.toedter.calendar.JDateChooser();
        txtdireccion = new javax.swing.JTextField();
        txttefefono = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatos = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.icon.checkmarkColor"));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdni.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dni", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtdni.setPreferredSize(new java.awt.Dimension(67, 40));
        jPanel2.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        txtnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtnombre.setMinimumSize(new java.awt.Dimension(64, 40));
        txtnombre.setPreferredSize(new java.awt.Dimension(67, 40));
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, -1));

        txtapellido1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido Paterno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtapellido1.setPreferredSize(new java.awt.Dimension(67, 40));
        jPanel2.add(txtapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, -1));

        txtapellido2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido Materno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtapellido2.setMinimumSize(new java.awt.Dimension(64, 40));
        txtapellido2.setPreferredSize(new java.awt.Dimension(67, 40));
        jPanel2.add(txtapellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 220, -1));

        cbxsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cbxsexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxsexo.setName(""); // NOI18N
        cbxsexo.setPreferredSize(new java.awt.Dimension(72, 50));
        jPanel2.add(cbxsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, 50));

        datenacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nacimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        datenacimiento.setMinimumSize(new java.awt.Dimension(92, 50));
        datenacimiento.setPreferredSize(new java.awt.Dimension(95, 50));
        jPanel2.add(datenacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 52));

        txtdireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtdireccion.setMinimumSize(new java.awt.Dimension(64, 40));
        txtdireccion.setPreferredSize(new java.awt.Dimension(67, 40));
        jPanel2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, -1));

        txttefefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txttefefono.setPreferredSize(new java.awt.Dimension(67, 40));
        jPanel2.add(txttefefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, -1));

        btnbuscar.setText("Buscar");
        jPanel2.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 220, -1));

        btnregistrar.setText("Registrar");
        jPanel2.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 220, -1));

        btneditar.setText("Editar");
        jPanel2.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 220, -1));

        btneliminar.setText("Eliminar");
        jPanel2.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 220, -1));

        btnlimpiar.setText("Limpiar");
        jPanel2.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 590));

        tbldatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbldatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 840, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btneditar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnlimpiar;
    public javax.swing.JButton btnregistrar;
    public javax.swing.JComboBox<String> cbxsexo;
    public com.toedter.calendar.JDateChooser datenacimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbldatos;
    public javax.swing.JTextField txtapellido1;
    public javax.swing.JTextField txtapellido2;
    public javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtdni;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JTextField txttefefono;
    // End of variables declaration//GEN-END:variables
}
