/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Nonename
 */
public class Matricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form Matricula
     */
    public Matricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        cbxaños = new javax.swing.JComboBox();
        cbxgrado = new javax.swing.JComboBox();
        cbxsalon = new javax.swing.JComboBox();
        lbestudiantes = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.icon.checkmarkColor"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Guardar");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 220, -1));

        jButton6.setText("Limpiar");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 220, -1));

        cbxaños.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        cbxaños.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Años", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxaños.setName(""); // NOI18N
        cbxaños.setPreferredSize(new java.awt.Dimension(72, 50));
        jPanel2.add(cbxaños, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 220, 50));

        cbxgrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        cbxgrado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxgrado.setName(""); // NOI18N
        cbxgrado.setPreferredSize(new java.awt.Dimension(72, 50));
        jPanel2.add(cbxgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 220, 50));

        cbxsalon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        cbxsalon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salon", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxsalon.setName(""); // NOI18N
        cbxsalon.setPreferredSize(new java.awt.Dimension(72, 50));
        jPanel2.add(cbxsalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 220, 50));

        lbestudiantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbestudiantes.setText("jLabel1");
        jPanel2.add(lbestudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 440, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cbxaños;
    public javax.swing.JComboBox cbxgrado;
    public javax.swing.JComboBox cbxsalon;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lbestudiantes;
    // End of variables declaration//GEN-END:variables
}
