/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Nonename
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        dktpanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        itmmenu = new javax.swing.JMenu();
        itmestudiante = new javax.swing.JMenuItem();
        itmcurso = new javax.swing.JMenuItem();
        itmdocente = new javax.swing.JMenuItem();
        itmsalon = new javax.swing.JMenuItem();
        itmgradocurso = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itmanios = new javax.swing.JMenuItem();
        itmdocentecurso = new javax.swing.JMenuItem();
        itmmatricula = new javax.swing.JMenuItem();
        itmcolaatencion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itmañomatricula = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dktpanelLayout = new javax.swing.GroupLayout(dktpanel);
        dktpanel.setLayout(dktpanelLayout);
        dktpanelLayout.setHorizontalGroup(
            dktpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        dktpanelLayout.setVerticalGroup(
            dktpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        itmmenu.setText("Registrar");

        itmestudiante.setText("Estudiantes");
        itmmenu.add(itmestudiante);

        itmcurso.setText("Cursos");
        itmmenu.add(itmcurso);

        itmdocente.setText("Docentes");
        itmmenu.add(itmdocente);

        itmsalon.setText("Salones");
        itmmenu.add(itmsalon);

        itmgradocurso.setText("Grado-Curso");
        itmmenu.add(itmgradocurso);

        jMenuBar1.add(itmmenu);

        jMenu3.setText("Gestion");

        itmanios.setText("Años academicos");
        itmanios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmaniosActionPerformed(evt);
            }
        });
        jMenu3.add(itmanios);

        itmdocentecurso.setText("Docente curso");
        jMenu3.add(itmdocentecurso);

        itmmatricula.setText("Matricula");
        jMenu3.add(itmmatricula);

        itmcolaatencion.setText("Matricula cola");
        jMenu3.add(itmcolaatencion);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Registros");

        itmañomatricula.setText("Año matricula");
        jMenu4.add(itmañomatricula);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dktpanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dktpanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmaniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmaniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmaniosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane dktpanel;
    public javax.swing.JMenuItem itmanios;
    public javax.swing.JMenuItem itmañomatricula;
    public javax.swing.JMenuItem itmcolaatencion;
    public javax.swing.JMenuItem itmcurso;
    public javax.swing.JMenuItem itmdocente;
    public javax.swing.JMenuItem itmdocentecurso;
    public javax.swing.JMenuItem itmestudiante;
    public javax.swing.JMenuItem itmgradocurso;
    public javax.swing.JMenuItem itmmatricula;
    public javax.swing.JMenu itmmenu;
    public javax.swing.JMenuItem itmsalon;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
